language: ruby

rvm:
  - 2.5.8

gemfile:
  - Gemfile

sudo: false

cache: bundler

before_script: "bundle update"

script: "bundle exec rake test"

after_success:
  - "bundle exec codeclimate-test-reporter"
